### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by ghost** [phallstrom/pow_default_app#1]
Hi there...

I've tried it, but the pow_default_app is not directly pointing well?

It says 404 not found whenever I try to access http://localhost.dev/

Please get into this.

**Comment by phallstrom** [comment]
Does $HOME/ .pow/default contain the directory or the contents of the directory. It should be the latter. That is .pow/default/config.ru should exist.

**Comment by phallstrom** [comment]
@shielasalamat Any update on this?

**Comment by phallstrom** [comment]
Re-open if this is still an issue.

**Comment by ghost** [comment]
Alright. This is solved already. Thanks a bunch.
